# wubi86.myself.config.dict.yaml
---
name: wubi86.config
version: "1.0"
sort: by_weight
use_preset_vocabulary: true
# 导入扩充词库
import_tables:
  - wubi86
  - wubi86_My
...

# Rime extended dictionary
 # encoding: utf-8
 
 # ---
 # name: extended
 # version: "2023-11-10"

 # import_tables:
  # - dicts/sougou_standard # 搜狗标准词库
  # - dicts/A # 扩充词库 A，此处 A 应为实际词库名称
  # - dicts/B # 扩充词库 B，此处 B 应为实际词库名称
 # ...
  # 如果是带有词条的词库，请在这里，按照编码格式添加词条